version: '3.8'

services:
  app:
    container_name: addressSearcherApp
    restart: on-failure
    networks:
      - db_network
    env_file:
      - googleapikey.env #Prepare your googleapikey.env with data "GOOGLE_API_KEYS=your key" to run application
                         #or use docker run --env GOOGLE_API_KEYS=your key
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: dockergoogleapidb
    image: postgres:16.1
    restart: on-failure
    networks:
      - db_network
    environment:
      POSTGRES_DB: dockergoogleapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local

networks:
  db_network:
    driver: bridge