server:
  port: 8080

# For Google Geocoding API
google:
  api:
    url: "https://maps.googleapis.com/maps/api/geocode/json?address="
    keys: "XYZ"
    location-sample-query: "24 Cybernetyki 9 Warszawa PL"

# Final values for query validation
forbidden:
  characters: "#,?,&,%,=,+"
max:
  address:
    length: 280

#For UUID sample
sample:
  id: "38400000-8cf0-11bd-b23e-10b96e4ef00d"

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:h2:mem:googleapi"
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: "/h2-console"

  # Hibernate
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    show-sql: true
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: "jdbc:postgresql://localhost:5432/googleapi"
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver

  # Hibernate
  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    show-sql: true
    hibernate:
      ddl-auto: update