version: 2.1

jobs:
  build-and-test:
    working_directory: ~/java
    docker:
      - image: cimg/openjdk:17.0.9
    steps:
      - checkout:
          path: ~/java
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Build
          command: mvn -B -DskipTests clean package -Dgoogle.api.keys=$GOOGLE_API_KEY
      - run:
          name: Tests
          command: mvn test -Dgoogle.api.keys=$GOOGLE_API_KEY

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-and-test